{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidData"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":2,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mgenetwork\/networkerror\/invaliddata"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/NetworkError\/invalidData","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error occuring when data is invalid."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidData"}],"title":"NetworkError.invalidData","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:10MGENetwork12NetworkErrorO11invalidDatayA2CmF","modules":[{"name":"MGENetwork"}]},"hierarchy":{"paths":[["doc:\/\/MGENetwork\/documentation\/MGENetwork","doc:\/\/MGENetwork\/documentation\/MGENetwork\/NetworkError"]]},"references":{"doc://MGENetwork/documentation/MGENetwork/NetworkError":{"role":"symbol","title":"NetworkError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkError"}],"abstract":[{"type":"text","text":"Error occurring upon network tasks."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/NetworkError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NetworkError"}],"url":"\/documentation\/mgenetwork\/networkerror"},"doc://MGENetwork/documentation/MGENetwork":{"role":"collection","title":"MGENetwork","abstract":[],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork","kind":"symbol","type":"topic","url":"\/documentation\/mgenetwork"},"doc://MGENetwork/documentation/MGENetwork/NetworkError/invalidData":{"role":"symbol","title":"NetworkError.invalidData","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidData"}],"abstract":[{"type":"text","text":"Error occuring when data is invalid."}],"identifier":"doc:\/\/MGENetwork\/documentation\/MGENetwork\/NetworkError\/invalidData","kind":"symbol","type":"topic","url":"\/documentation\/mgenetwork\/networkerror\/invaliddata"}}}